## roles/ansible-role-awx/vars/CentOS-7.yml
# vim:ft=yaml.ansible:
---
awx_python_interpreter: python
awx_package_dependencies:
  - git
  - ansible
  - docker
  - python2-pip
  - python3-pip
  - libselinux-python
  - nodejs

...
